db.driver=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://localhost:3306/phong_kham_thu_y?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
db.username=root
db.password=123456
db.pool.initialPoolSize=5
db.pool.minPoolSize=5